import { MigrationInterface, QueryRunner } from 'typeorm';

export class PaymentWebhooksEntityAlignment1700000000003 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_webhook_status') THEN
    CREATE TYPE payment_webhook_status AS ENUM ('pending', 'processing', 'success', 'failed');
  END IF;
END $$;
    `);

    await queryRunner.query(`
CREATE TABLE IF NOT EXISTS payment_webhooks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(50) NOT NULL,
  event_type VARCHAR(256) NOT NULL,
  payment_id INTEGER NULL,
  status payment_webhook_status NOT NULL DEFAULT 'pending',
  webhook_payload JSONB NOT NULL,
  signature VARCHAR(255) NULL,
  processed_at TIMESTAMP NULL,
  error_message TEXT NULL,
  retry_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
    `);

    await queryRunner.query(`
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_payment_webhooks_payment_id'
  ) THEN
    ALTER TABLE payment_webhooks
    ADD CONSTRAINT fk_payment_webhooks_payment_id
    FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL;
  END IF;
END $$;
    `);

    await queryRunner.query(`
CREATE INDEX IF NOT EXISTS idx_payment_webhooks_provider ON payment_webhooks(provider);
CREATE INDEX IF NOT EXISTS idx_payment_webhooks_status ON payment_webhooks(status);
CREATE INDEX IF NOT EXISTS idx_payment_webhooks_created_at ON payment_webhooks(created_at);
CREATE INDEX IF NOT EXISTS idx_payment_webhooks_payment_id ON payment_webhooks(payment_id);
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS payment_webhooks;`);
    await queryRunner.query(`DROP TYPE IF EXISTS payment_webhook_status;`);
  }
}
