import { MigrationInterface, QueryRunner } from 'typeorm';

export class AuthSessionWallet1700000000006 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
CREATE TABLE IF NOT EXISTS auth_otp_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  code_hash TEXT NOT NULL,
  purpose VARCHAR(50) NOT NULL DEFAULT 'login',
  expires_at TIMESTAMP NOT NULL,
  consumed_at TIMESTAMP DEFAULT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
    `);

    await queryRunner.query(`
CREATE INDEX IF NOT EXISTS idx_auth_otp_requests_email ON auth_otp_requests(email);
CREATE INDEX IF NOT EXISTS idx_auth_otp_requests_expires_at ON auth_otp_requests(expires_at);
CREATE INDEX IF NOT EXISTS idx_auth_otp_requests_consumed_at ON auth_otp_requests(consumed_at);
    `);

    await queryRunner.query(`
CREATE TABLE IF NOT EXISTS user_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  refresh_token_hash TEXT NOT NULL,
  device_fingerprint TEXT NOT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  expires_at TIMESTAMP NOT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
    `);

    await queryRunner.query(`
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_device_fingerprint ON user_sessions(device_fingerprint);
CREATE INDEX IF NOT EXISTS idx_user_sessions_expires_at ON user_sessions(expires_at);
    `);

    await queryRunner.query(`
CREATE TABLE IF NOT EXISTS vote_wallets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  free_vote_used BOOLEAN NOT NULL DEFAULT FALSE,
  paid_votes_purchased INTEGER NOT NULL DEFAULT 0,
  paid_votes_used INTEGER NOT NULL DEFAULT 0,
  daily_paid_used INTEGER NOT NULL DEFAULT 0,
  last_vote_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_vote_wallets_user_event_category UNIQUE (user_id, event_id, category_id)
);
    `);

    await queryRunner.query(`
CREATE INDEX IF NOT EXISTS idx_vote_wallets_user_id ON vote_wallets(user_id);
CREATE INDEX IF NOT EXISTS idx_vote_wallets_event_id ON vote_wallets(event_id);
CREATE INDEX IF NOT EXISTS idx_vote_wallets_category_id ON vote_wallets(category_id);
    `);

    await queryRunner.query(`
CREATE TABLE IF NOT EXISTS vote_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  wallet_id INTEGER NOT NULL REFERENCES vote_wallets(id) ON DELETE CASCADE,
  contestant_id INTEGER NOT NULL REFERENCES contestants(id) ON DELETE CASCADE,
  vote_type VARCHAR(10) NOT NULL CHECK (vote_type IN ('FREE', 'PAID')),
  payment_reference TEXT DEFAULT NULL,
  amount_paid NUMERIC(10,2) DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  device_fingerprint TEXT DEFAULT NULL,
  risk_score INTEGER DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
    `);

    await queryRunner.query(`
CREATE INDEX IF NOT EXISTS idx_vote_transactions_user_id ON vote_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_vote_transactions_wallet_id ON vote_transactions(wallet_id);
CREATE INDEX IF NOT EXISTS idx_vote_transactions_contestant_id ON vote_transactions(contestant_id);
CREATE INDEX IF NOT EXISTS idx_vote_transactions_created_at ON vote_transactions(created_at);
    `);

    await queryRunner.query(`
CREATE TABLE IF NOT EXISTS risk_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_id INTEGER DEFAULT NULL REFERENCES events(id) ON DELETE SET NULL,
  risk_type VARCHAR(50) NOT NULL,
  risk_score INTEGER NOT NULL DEFAULT 0,
  ip_address VARCHAR(45) DEFAULT NULL,
  device_fingerprint TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
    `);

    await queryRunner.query(`
CREATE INDEX IF NOT EXISTS idx_risk_logs_user_id ON risk_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_risk_logs_event_id ON risk_logs(event_id);
CREATE INDEX IF NOT EXISTS idx_risk_logs_risk_type ON risk_logs(risk_type);
CREATE INDEX IF NOT EXISTS idx_risk_logs_created_at ON risk_logs(created_at);
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS risk_logs;`);
    await queryRunner.query(`DROP TABLE IF EXISTS vote_transactions;`);
    await queryRunner.query(`DROP TABLE IF EXISTS vote_wallets;`);
    await queryRunner.query(`DROP TABLE IF EXISTS user_sessions;`);
    await queryRunner.query(`DROP TABLE IF EXISTS auth_otp_requests;`);
  }
}

