import { MigrationInterface, QueryRunner } from 'typeorm';

export class WalletCreditAllocation1700000000007 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
CREATE TABLE IF NOT EXISTS wallet_vote_credits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id INTEGER NOT NULL REFERENCES vote_wallets(id) ON DELETE CASCADE,
  payment_id INTEGER NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
  votes_credited INTEGER NOT NULL DEFAULT 0,
  votes_remaining INTEGER NOT NULL DEFAULT 0,
  amount NUMERIC(10,2) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
    `);

    await queryRunner.query(`
CREATE UNIQUE INDEX IF NOT EXISTS uq_wallet_vote_credits_payment_id
  ON wallet_vote_credits(payment_id);
CREATE INDEX IF NOT EXISTS idx_wallet_vote_credits_wallet_id
  ON wallet_vote_credits(wallet_id);
CREATE INDEX IF NOT EXISTS idx_wallet_vote_credits_votes_remaining
  ON wallet_vote_credits(votes_remaining);
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS wallet_vote_credits;`);
  }
}

