import { Event, EventStats } from '@/types/event';

export const mockEvents: Event[] = [
  {
    id: 'event-1',
    slug: 'miss-africa-2026',
    name: 'Miss Africa 2026',
    description: 'The most prestigious beauty pageant across the African continent.',
    tagline: 'Beauty, Elegance, and African Pride',
    start_date: '2026-04-01',
    end_date: '2026-04-30',
    status: 'LIVE',
    banner_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=1200&h=400&fit=crop',
    voting_rules: 'One free vote per category, additional votes available for purchase.',
    vote_price: 2.5,
    max_votes_per_transaction: 100,
    organizer_name: 'African Beauty Foundation',
    location: 'Pan-African',
    season_year: 2026,
    is_live: true,
  },
  {
    id: 'event-2',
    slug: 'miss-africa-2025',
    name: 'Miss Africa 2025',
    description: 'Previous season of Miss Africa pageant.',
    tagline: 'Celebrating African Beauty',
    start_date: '2025-04-01',
    end_date: '2025-04-30',
    status: 'ARCHIVED',
    banner_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&h=400&fit=crop',
    voting_rules: 'One free vote per category, additional votes available for purchase.',
    vote_price: 2.5,
    max_votes_per_transaction: 100,
    organizer_name: 'African Beauty Foundation',
    location: 'Pan-African',
    season_year: 2025,
    is_live: false,
  },
  {
    id: 'event-3',
    slug: 'mr-africa-2026',
    name: 'Mr Africa 2026',
    description: 'Celebrating the finest male talents and charisma across Africa.',
    tagline: 'Strength, Character, and Excellence',
    start_date: '2026-06-01',
    end_date: '2026-06-30',
    status: 'UPCOMING',
    banner_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=400&fit=crop',
    voting_rules: 'One free vote per category, additional votes available for purchase.',
    vote_price: 2.5,
    max_votes_per_transaction: 100,
    organizer_name: 'African Excellence Foundation',
    location: 'Pan-African',
    season_year: 2026,
    is_live: false,
  },
  {
    id: 'event-4',
    slug: 'talent-africa-2026',
    name: 'Talent Africa 2026',
    description: 'Showcase for extraordinary talents across music, dance, and performing arts.',
    tagline: 'Where African Talent Shines',
    start_date: '2026-07-01',
    end_date: '2026-08-31',
    status: 'UPCOMING',
    banner_url: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=1200&h=400&fit=crop',
    voting_rules: 'One free vote per category, additional votes available for purchase.',
    vote_price: 3.0,
    max_votes_per_transaction: 100,
    organizer_name: 'African Entertainment Network',
    location: 'Pan-African',
    season_year: 2026,
    is_live: false,
  },
  {
    id: 'event-5',
    slug: 'campus-star-east-africa-2026',
    name: 'Campus Star East Africa 2026',
    description: 'A live regional showdown featuring top university talents from East Africa.',
    tagline: 'Regional Voices. Continental Impact.',
    start_date: '2026-02-10',
    end_date: '2026-03-15',
    status: 'LIVE',
    banner_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&h=400&fit=crop',
    voting_rules: 'One free vote per category, additional votes available for purchase.',
    vote_price: 2.0,
    max_votes_per_transaction: 100,
    organizer_name: 'Campus Star Network',
    location: 'East Africa',
    season_year: 2026,
    is_live: true,
  },
  {
    id: 'event-6',
    slug: 'africa-dance-championship-2026',
    name: 'Africa Dance Championship 2026',
    description: 'Live dance battles from elite crews across the continent.',
    tagline: 'Rhythm. Precision. Glory.',
    start_date: '2026-01-25',
    end_date: '2026-03-20',
    status: 'LIVE',
    banner_url: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=1200&h=400&fit=crop',
    voting_rules: 'One free vote per category, additional votes available for purchase.',
    vote_price: 2.8,
    max_votes_per_transaction: 100,
    organizer_name: 'African Arts League',
    location: 'Pan-African',
    season_year: 2026,
    is_live: true,
  },
  {
    id: 'event-7',
    slug: 'africa-tech-idol-2026',
    name: 'Africa Tech Idol 2026',
    description: 'Upcoming innovation and creator showcase for rising digital talent.',
    tagline: 'Innovation Meets Influence.',
    start_date: '2026-09-01',
    end_date: '2026-10-10',
    status: 'UPCOMING',
    banner_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&h=400&fit=crop',
    voting_rules: 'One free vote per category, additional votes available for purchase.',
    vote_price: 3.2,
    max_votes_per_transaction: 100,
    organizer_name: 'Africa Future Labs',
    location: 'Pan-African',
    season_year: 2026,
    is_live: false,
  },
];

export const mockEventStats: EventStats = {
  total_votes: 1245678,
  total_contestants: 48,
  active_categories: 12,
  votes_today: 23475,
};

export const mockArchivedEvents: Event[] = [
  {
    id: 'event-archive-1',
    slug: 'miss-africa-2024',
    name: 'Miss Africa 2024',
    description: 'The 2024 edition of Miss Africa pageant.',
    start_date: '2024-04-01',
    end_date: '2024-04-30',
    status: 'ARCHIVED',
    banner_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=1200&h=400&fit=crop',
    vote_price: 2.5,
    max_votes_per_transaction: 100,
    season_year: 2024,
    is_live: false,
  },
  {
    id: 'event-archive-2',
    slug: 'miss-africa-2023',
    name: 'Miss Africa 2023',
    description: 'The 2023 edition of Miss Africa pageant.',
    start_date: '2023-04-01',
    end_date: '2023-04-30',
    status: 'ARCHIVED',
    banner_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&h=400&fit=crop',
    vote_price: 2.0,
    max_votes_per_transaction: 100,
    season_year: 2023,
    is_live: false,
  },
];
