import { MigrationInterface, QueryRunner } from 'typeorm';

export class EventsContestants0003 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
-- Events & Contestants
CREATE TABLE events (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  description TEXT,
  status event_status NOT NULL DEFAULT 'draft',
  creator_id INTEGER REFERENCES users(id),
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  voting_start TIMESTAMP,
  voting_end TIMESTAMP,
  rules TEXT,
  terms_and_conditions TEXT,
  visibility VARCHAR(20) DEFAULT 'public',
  allow_write_ins BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  category_order INTEGER DEFAULT 0,
  voting_enabled BOOLEAN DEFAULT TRUE,
  public_voting BOOLEAN DEFAULT TRUE,
  paid_voting BOOLEAN DEFAULT FALSE,
  minimum_vote_amount NUMERIC(10,2) DEFAULT 0.00,
  accept_write_ins BOOLEAN DEFAULT FALSE,
  daily_vote_limit INTEGER,
  max_votes_per_user INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE event_locks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id INTEGER REFERENCES events(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  is_locked BOOLEAN DEFAULT FALSE,
  locked_at TIMESTAMP,
  locked_reason TEXT,
  locked_by INTEGER REFERENCES users(id)
);

CREATE TABLE event_sponsors (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  sponsor_name VARCHAR(255),
  sponsorship_level VARCHAR(50),
  amount NUMERIC(12,2),
  logo_url VARCHAR(512)
);

CREATE TABLE contestants (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(255),
  phone_number VARCHAR(20),
  date_of_birth DATE,
  biography TEXT,
  profile_image_url VARCHAR(512),
  banner_image_url VARCHAR(512),
  status contestant_status NOT NULL DEFAULT 'draft',
  verification_status verification_status NOT NULL DEFAULT 'unverified',
  verified_at TIMESTAMP,
  verified_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  vote_count INTEGER DEFAULT 0,
  paid_vote_count INTEGER DEFAULT 0,
  free_vote_count INTEGER DEFAULT 0,
  total_revenue NUMERIC(12,2) DEFAULT 0.00,
  display_order INTEGER,
  is_featured BOOLEAN DEFAULT FALSE,
  twitter_handle VARCHAR(100),
  instagram_handle VARCHAR(100),
  facebook_url VARCHAR(512),
  tiktok_handle VARCHAR(100),
  youtube_channel VARCHAR(512),
  website_url VARCHAR(512),
  linkedin_profile VARCHAR(512),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contestant_applications (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(255),
  phone_number VARCHAR(20),
  date_of_birth DATE,
  biography TEXT,
  application_status application_status NOT NULL DEFAULT 'pending',
  rejection_reason TEXT,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP,
  reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE contestant_media_gallery (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contestant_id INTEGER NOT NULL REFERENCES contestants(id) ON DELETE CASCADE,
  media_type VARCHAR(20) DEFAULT 'photo',
  media_url VARCHAR(512) NOT NULL,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
DROP TABLE IF EXISTS contestant_media_gallery;
DROP TABLE IF EXISTS contestant_applications;
DROP TABLE IF EXISTS contestants;
DROP TABLE IF EXISTS event_sponsors;
DROP TABLE IF EXISTS event_locks;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS events;
    `);
  }
}

export default EventsContestants0003;
