import { MigrationInterface, QueryRunner } from 'typeorm';

export class PaymentsWebhooks0004 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
-- Payments & Webhooks
CREATE TABLE payments (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  voter_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  contestant_id INTEGER NOT NULL REFERENCES contestants(id) ON DELETE CASCADE,
  amount NUMERIC(12,2) NOT NULL,
  currency VARCHAR(3) DEFAULT 'USD',
  provider payment_provider NOT NULL,
  status payment_status NOT NULL DEFAULT 'pending',
  provider_transaction_id VARCHAR(256),
  payment_method VARCHAR(50),
  votes_purchased INTEGER,
  receipt_url VARCHAR(512),
  ip_address VARCHAR(45),
  device_fingerprint VARCHAR(256),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payment_providers (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL UNIQUE,
  provider_type VARCHAR(50),
  api_key VARCHAR(512),
  secret_key VARCHAR(512),
  webhook_url VARCHAR(512),
  status payment_provider_status DEFAULT 'active',
  environment payment_provider_env DEFAULT 'test',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payment_limits (
  event_id INTEGER REFERENCES events(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  daily_limit NUMERIC(12,2),
  weekly_limit NUMERIC(12,2),
  monthly_limit NUMERIC(12,2),
  per_transaction_max NUMERIC(12,2),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refund_requests (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  payment_id INTEGER NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  amount NUMERIC(12,2),
  status refund_status NOT NULL DEFAULT 'pending',
  approved_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMP,
  rejected_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  rejected_at TIMESTAMP,
  rejection_reason TEXT,
  processed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE crypto_payments (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  payment_id INTEGER NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
  wallet_address VARCHAR(256),
  transaction_hash VARCHAR(256),
  blockchain_confirmation INTEGER DEFAULT 0,
  amount_in_crypto NUMERIC(18,8),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE crypto_wallets (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  wallet_address VARCHAR(256),
  cryptocurrency VARCHAR(20),
  balance NUMERIC(18,8),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Webhooks & integration tables
CREATE TABLE webhook_events (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_type VARCHAR(100) NOT NULL,
  provider webhook_provider,
  payload JSONB NOT NULL,
  status webhook_status DEFAULT 'received',
  retry_count INTEGER DEFAULT 0,
  last_retry_at TIMESTAMP,
  next_retry_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE webhook_attempts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  webhook_event_id INTEGER NOT NULL REFERENCES webhook_events(id) ON DELETE CASCADE,
  attempt_number INTEGER,
  response_status_code INTEGER,
  response_body TEXT,
  success BOOLEAN DEFAULT FALSE,
  error_message TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE webhook_failures (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  webhook_event_id INTEGER NOT NULL REFERENCES webhook_events(id) ON DELETE CASCADE,
  error_message TEXT,
  failure_reason VARCHAR(255),
  is_resolved BOOLEAN DEFAULT FALSE,
  resolved_at TIMESTAMP,
  next_retry_at TIMESTAMP,
  max_retries_reached BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE webhook_audit (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  transaction_id VARCHAR(256),
  provider webhook_provider,
  status webhook_event_status DEFAULT 'success',
  audit_type webhook_audit_type,
  payment_id INTEGER,
  vote_id INTEGER,
  details TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE webhook_rate_limit (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  provider webhook_provider,
  period_start TIMESTAMP,
  period_end TIMESTAMP,
  request_count INTEGER DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE webhook_secrets (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  provider VARCHAR(100),
  secret VARCHAR(512),
  version INTEGER DEFAULT 1,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  rotated_at TIMESTAMP
);

CREATE TABLE webhook_signature_logs (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  webhook_event_id INTEGER NOT NULL REFERENCES webhook_events(id) ON DELETE CASCADE,
  signature_received VARCHAR(512),
  signature_calculated VARCHAR(512),
  signature_valid BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stripe_webhooks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  payment_id INTEGER REFERENCES payments(id) ON DELETE SET NULL,
  stripe_event_id VARCHAR(256),
  event_type VARCHAR(100),
  event_data JSONB,
  processed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
DROP TABLE IF EXISTS stripe_webhooks;
DROP TABLE IF EXISTS webhook_signature_logs;
DROP TABLE IF EXISTS webhook_secrets;
DROP TABLE IF EXISTS webhook_rate_limit;
DROP TABLE IF EXISTS webhook_audit;
DROP TABLE IF EXISTS webhook_failures;
DROP TABLE IF EXISTS webhook_attempts;
DROP TABLE IF EXISTS webhook_events;
DROP TABLE IF EXISTS crypto_wallets;
DROP TABLE IF EXISTS crypto_payments;
DROP TABLE IF EXISTS refund_requests;
DROP TABLE IF EXISTS payment_limits;
DROP TABLE IF EXISTS payment_providers;
DROP TABLE IF EXISTS payments;
    `);
  }
}

export default PaymentsWebhooks0004;
